primaryLocation         = "westeurope"
secondaryLocation       = "eastus"
globalResourcePrefix    = "nca"
primaryResourcePrefix   = "nca-eu"
secondaryResourcePrefix = "nca-us"
storageName             = "ncafiles"
adminName               = "ncuser"
adminPass               = "539SUKTWgmh=LZ9s"
