primaryLocation         = "westeurope"
secondaryLocation       = "eastus"
globalResourcePrefix    = "ncag"
primaryResourcePrefix   = "ncag-eu"
secondaryResourcePrefix = "ncag-us"
storageName             = "ncagfiles"
adminName               = "ncaguser"
adminPass               = "R4nd0mP455w0rD"
