primaryLocation         = "westeurope"
secondaryLocation       = "eastus"
globalResourcePrefix    = "ncatest"
primaryResourcePrefix   = "ncatest-eu"
secondaryResourcePrefix = "ncatest-us"
storageName             = "ncatestfiles"
adminName               = "ncauser"
adminPass               = "539SUKTWgmh=LZ9s"
